### ISSUE TITLE
Recommended auth framework that follows these principles?

### ISSUE THREAD

**Issue by robertlagrant** [mmerickel/pyramid_auth_demo#5]
Not an issue with your demo (which is very helpful - thanks), but more wondering if there's a good pyramid framework that implements these basic principles (especially one that has a ready integration with SQLAlchemy).

I'm half-tempted to try writing one myself based on this tutorial, but I know I've got a long way to go to write something good in Pyramid, and wondered if there's something already available.

**Comment by mmerickel** [comment]
Sorry for the delay on this but I'm not aware of anything... the closest thing I know about is the Kotti framework which has nice SQLAlchemy models for handling ACLs but it is not reusable outside of Kotti without extra work.
